version: 0.0
os: linux
files:
  - source: /public
    destination: /var/www/front/public

  - source: /hosts/conf.d
    destination: /etc/nginx/conf.d
  
  - source: /tailwindcss
    destination: /home/ec2-user/tailwindcss

hooks:
  AfterInstall:
    - location: scripts/set_owner
      timeout: 5
      runas: root
    - location: scripts/install_dependencies
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_server
      timeout: 10
      runas: root
  ValidateService: 
    - location: scripts/validate_server
      timeout: 30
      runas: ec2-user