name: Build TailwindCSS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build Tailwind CSS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: cd tailwindcss
      - run: npm install -D tailwindcss
      - run: npx tailwindcss init
      - run: npx tailwindcss -i ${GITHUB_ACTION_PATH}/tailwindcss/src/input.css -o ${GITHUB_ACTION_PATH}/public/resources/style.css

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
          BRANCH: compiled  # 배포될 브랜치
          FOLDER: ${GITHUB_ACTION_PATH} # 이 폴더에 있는 파일을 배포
