name: Build TailwindCSS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
    continue-on-error: ${{ matrix.php == '8.2' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup ini config
        id: set_ini
        run: echo 'PHP_INI=error_reporting=-1, display_errors=On' >> $GITHUB_OUTPUT


      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: none
          tools: cs2pr
      
      - name: Install Composer dependencies - with ignore platform
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --ignore-platform-reqs

      - name: Install PHPSniffer
        run: git clone https://github.com/squizlabs/PHP_CodeSniffer.git && cd PHP_CodeSniffer && php bin/phpcbf /home/runner/work/front/front/public

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Build Tailwind CSS
        run: cd tailwindcss && npm install -D tailwindcss && npx tailwindcss init && npx tailwindcss -i /home/runner/work/front/front/tailwindcss/src/input.css -o /home/runner/work/front/front/public/resources/style.css --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
          BRANCH: compiled  # 배포될 브랜치
          FOLDER: /home/runner/work/front/front # 이 폴더에 있는 파일을 배포
